name: Continuous Integration and Delivery Test

on:
  push:
    branches:
      - test

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2.3.4
      - name: test1
        uses: kceb/pull-request-url-action@v1
        id: pr-url
      - run: |
          echo "${{ steps.pr-url.outputs.url }}"

